name: Init Action

on:
    push:
        branches:
            - main      
    pull_request:
        branches:
            - main       

jobs:
    say-hello:
        runs-on: ubuntu-latest   
        steps:
            - name: Checkout 
              uses: actions/checkout@v3

            - name: Print Hello World
              run: echo "hello-world"

    build:
        runs-on: ${{ matrix.runner }}
        strategy:
            matrix:
                runner: [ubuntu-latest, windows-latest, macos-latest]
                node: [14, 16, 18, 20]

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            # - name: Set NodeJS Version
            #   uses: actions/setup-node@v3
            #   with:
            #     node-version: ${{ matrix.node }}

            - name: Attempt to setup NodeJS version
              id: setup_node
              run: |
                if ! actions/setup-node@v3 --node-version=${{ matrix.node }}; then
                  echo "NodeJS Version ${{ matrix.node }} is not available on ${{ matrix.runner }}."
                  echo "NODE_VERSION_AVAILABLE=false" >> $GITHUB_ENV
                else
                  echo "NodeJS Version ${{ matrix.node }} is set up on ${{ matrix.runner }}."
                  echo "NODE_VERSION_AVAILABLE=true" >> $GITHUB_ENV
                fi

            # - name: Attempt to setup NodeJS version
            #   id: setup_node
            #   run: |
            #     echo "Setting up NodeJS version ${{ matrix.node }} on ${{ matrix.runner }}"
            #     try {
            #       actions/setup-node@v3 --node-version=${{ matrix.node }}
            #       echo "Node.js version ${{ matrix.node }} is set up on ${{ matrix.runner }}."
            #       echo "NODE_VERSION_AVAILABLE=true" >> $env:GITHUB_ENV
            #     } catch {
            #       echo "Node.js version ${{ matrix.node }} is not available on ${{ matrix.runner }}."
            #       echo "NODE_VERSION_AVAILABLE=false" >> $env:GITHUB_ENV
            #     }
            #   shell: pwsh

            # - name: Attempt to set up Node.js
            #   id: setup_node
            #   run: |
            #     if [ "${{ runner.os }}" == "Windows" ]; then
            #       echo "Setting up Node.js version ${{ matrix.node }} on ${{ matrix.runner }}"
            #       if ! actions/setup-node@v3 --node-version=${{ matrix.node }}; then
            #       echo "Node.js version ${{ matrix.node }} is not available on ${{ matrix.runner }}."
            #       echo "NODE_VERSION_AVAILABLE=false" >> $env:GITHUB_ENV
            #     else
            #       echo "Node.js version ${{ matrix.node }} is set up on ${{ matrix.runner }}."
            #       echo "NODE_VERSION_AVAILABLE=true" >> $env:GITHUB_ENV
            #     fi
            #     else
            #       echo "Setting up Node.js version ${{ matrix.node }} on ${{ matrix.runner }}"
            #       if ! actions/setup-node@v3 --node-version=${{ matrix.node }}; then
            #       echo "Node.js version ${{ matrix.node }} is not available on ${{ matrix.runner }}."
            #       echo "NODE_VERSION_AVAILABLE=false" >> $GITHUB_ENV
            #     else
            #       echo "Node.js version ${{ matrix.node }} is set up on ${{ matrix.runner }}."
            #       echo "NODE_VERSION_AVAILABLE=true" >> $GITHUB_ENV
            #     fi
            #     fi
            #   shell: bash            

            - name: Restore NodeJS modules cache
              if: env.NODE_VERSION_AVAILABLE == 'true'
              uses: actions/cache@v3
              with:
                path: ~/.npm
                key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                  ${{ runner.os }}-node${{ matrix.node }}-
                  ${{ runner.os }}-node-
                  ${{ runner.os }}-

            - name: Install NodeJS Dependencies
              if: env.NODE_VERSION_AVAILABLE == 'true'
              run: npm install

            - name: Save NodeJS modules cache
              if: env.NODE_VERSION_AVAILABLE == 'true'
              uses: actions/cache@v3
              with:
                path: ~/.npm
                key: ${{ matrix.runner }}-node-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}

            # - name: Execute tests
            #   run: npm test

            - name: Test secret
              run: echo "The secret is ${{ secrets.API_KEY }}"

            - name: Run tests and capture logs
              if: env.NODE_VERSION_AVAILABLE == 'true'
              id: test
              run: |
                npm test > test.log || true
                echo "::set-output name=log-path::test.log"

            - name: Upload logs as artifact
              if: env.NODE_VERSION_AVAILABLE == 'true'
              uses: actions/upload-artifact@v3
              with:
                name: test-logs
                path: ${{ steps.test.outputs.log-path }}