name: Init Action

on:
    push:
        branches:
            - main

jobs:
    say-hello:
        name: Say Hello World
        runs-on: ubuntu-latest   
        steps:
            - name: Print Hello World
              id: print-hello-world
              uses: actions/checkout@v2