name: Init Action

# Inicia acao automaticamente em qualquer push na branch main
# on:
#     push:
#         branches:
#             - main

# A acao somente é iniciada manualmente
on: 
    workflow_dispatch:
        inputs:
            who-to-greet:
                description: Who to greet in the log
                required: true
                default: 'World'
                type: string

jobs:
    say-hello:
        name: Say Hello World
        runs-on: ubuntu-latest   
        steps:
            - name: Print Hello World
              id: print-hello-world
              uses: actions/checkout@v2
              with:
                who-to-greet: ${{ inputs.who-to-greet }}