name: Init Action

on:
    push:
        branches:
            - main      
    pull_request:
        branches:
            - main       

jobs:
    say-hello:
        runs-on: ubuntu-latest   
        steps:
            - name: Checkout 
              uses: actions/checkout@v3

            - name: Print Hello World
              run: echo "hello-world"

    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]

    # install-nodejs-dependencies:
        # runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set NodeJS Version
              uses: actions/setup-node@v3
              with:
                node-version: '20'

            - name: Install NodeJS Dependencies
              run: npm install
                      
            - name: Execute tests
              run: npm test

            - name: Test secret
              run: echo "The secret is ${{ secrets.API_KEY }}"