name: Init Action

on:
    push:
        branches:
            - main             

jobs:
    say-hello:
        runs-on: ubuntu-latest   
        steps:
            - name: Checkout 
              uses: actions/checkout@v2

            - name: Print Hello World
              run: echo "hello-world"